"""initial schema — 클럽 리브랜딩(Stargayte)에 맞춰 저장소를 새로 시작하며, 기존
52개 마이그레이션이 누적으로 만들어온 최종 스키마를 하나의 베이스라인으로 합쳤다.
(구 stargate-club-api 저장소에 예전 마이그레이션 이력이 그대로 남아있다.)

Revision ID: 0001
Revises:
Create Date: 2026-07-13

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_version_state',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('active_version', sa.String(length=8), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('env_vars',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('members',
    sa.Column('pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('battletag', sa.String(length=50), nullable=False),
    sa.Column('insta', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['members.pk'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['members.pk'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('battletag'),
    sa.UniqueConstraint('id')
    )
    op.create_table('access_history',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('member_pk', sa.BigInteger(), nullable=False),
    sa.Column('logged_in_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('screen_code', sa.String(length=32), nullable=True),
    sa.CheckConstraint("screen_code IS NULL OR screen_code IN ('ranking', 'match', 'official', 'stats', 'members', 'accessHistory', 'imageSettings', 'menuPermissions', 'userMapping')", name='ck_access_history_screen_code'),
    sa.ForeignKeyConstraint(['member_pk'], ['members.pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_access_history_member_pk', 'access_history', ['member_pk'])
    op.create_index('idx_access_history_member_screen', 'access_history', ['member_pk', 'screen_code'])
    op.create_table('image_settings',
    sa.Column('slot', sa.String(length=30), nullable=False),
    sa.Column('icon_type', sa.String(length=10), nullable=False),
    sa.Column('icon_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['members.pk'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['members.pk'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('slot')
    )
    op.create_table('matches',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('match_no', sa.String(length=14), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('match_type', sa.String(length=4), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['members.pk'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['members.pk'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_no')
    )
    op.create_index('idx_matches_match_date', 'matches', ['match_date'])
    op.create_table('member_roles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('member_pk', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_pk'], ['members.pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_pk', 'role', name='uq_member_roles_member_role')
    )
    op.create_index('idx_member_roles_member_pk', 'member_roles', ['member_pk'])
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('member_pk', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_pk'], ['members.pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_refresh_tokens_member_pk', 'refresh_tokens', ['member_pk'])
    op.create_table('replay_aliases',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('raw_name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('member_pk', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(kind = 'member') = (member_pk IS NOT NULL)", name='ck_replay_aliases_member_pk_matches_kind'),
    sa.CheckConstraint("kind IN ('member', 'computer', 'unregistered')", name='ck_replay_aliases_kind'),
    sa.ForeignKeyConstraint(['member_pk'], ['members.pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_name', name='uq_replay_aliases_raw_name')
    )
    op.create_index('idx_replay_aliases_member_pk', 'replay_aliases', ['member_pk'])
    op.create_table('challenges',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('match_type', sa.String(length=4), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('result_match_id', sa.BigInteger(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['members.pk'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['result_match_id'], ['matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['members.pk'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_attachments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['members.pk'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['members.pk'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('match_participants',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('team', sa.String(length=5), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=False),
    sa.Column('race', sa.String(length=20), nullable=False),
    sa.Column('apm', sa.Integer(), nullable=True),
    sa.Column('eapm', sa.Integer(), nullable=True),
    sa.Column('cmd_count', sa.Integer(), nullable=True),
    sa.Column('effective_cmd_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['members.pk'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['members.pk'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team', 'position')
    )
    op.create_index('idx_match_participants_match_id', 'match_participants', ['match_id'])
    op.create_table('match_results',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('map_name', sa.String(length=150), nullable=True),
    sa.Column('game_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('challenge_participants',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.BigInteger(), nullable=False),
    sa.Column('member_pk', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('response', sa.String(length=10), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.CheckConstraint("response IN ('pending','accepted','rejected')", name='ck_challenge_participants_response'),
    sa.CheckConstraint("side IN ('creator','target')", name='ck_challenge_participants_side'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_pk'], ['members.pk'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'member_pk', name='uq_challenge_participants_challenge_member')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_participants')
    op.drop_table('match_results')
    op.drop_index('idx_match_participants_match_id', table_name='match_participants')
    op.drop_table('match_participants')
    op.drop_table('match_attachments')
    op.drop_table('challenges')
    op.drop_index('idx_replay_aliases_member_pk', table_name='replay_aliases')
    op.drop_table('replay_aliases')
    op.drop_index('idx_refresh_tokens_member_pk', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_member_roles_member_pk', table_name='member_roles')
    op.drop_table('member_roles')
    op.drop_index('idx_matches_match_date', table_name='matches')
    op.drop_table('matches')
    op.drop_table('image_settings')
    op.drop_index('idx_access_history_member_screen', table_name='access_history')
    op.drop_index('idx_access_history_member_pk', table_name='access_history')
    op.drop_table('access_history')
    op.drop_table('members')
    op.drop_table('env_vars')
    op.drop_table('app_version_state')
    # ### end Alembic commands ###
